### ISSUE TITLE
Linear_programs. task2 returns wrong results.

### ISSUE THREAD

**Issue by Andrei-Luksha2** [YuriZayets/Java_Basic#1]
task2(2,1,1) should return -6, but returns -1.

https://github.com/YuriZayets/Java_Basic/blob/23df63bbbe0cabc4454662b42d0f0b863112da88/Basics_of_software_code_development/Linear_programs.java#L12

**Comment by YuriZayets** [comment]
fixed it, should be like
return ((b + Math.sqrt(b * b + 4 * a * c)) / **(**2 * a**)**) - **Math.pow(a, 3)** * c + Math.pow(b, -2);
