### ISSUE TITLE
wrong formula in taskThree

### ISSUE THREAD

**Issue by Andrei-Luksha2** [YuriZayets/Java_Basic#3]
The formula is wrong: https://github.com/YuriZayets/Java_Basic/blob/8015ebec2805ceb1cd26fc69db51db6716baef71/Basics_of_software_code_development/Linear_programs.java#L18

**Comment by YuriZayets** [comment]
Fixed a lapse in Fourth Math.class call, should be:

 return ((Math.sin(a) + Math.cos(b)) / (Math.cos(a) - Math.**sin**(b))) * Math.tan(a * b);
