### ISSUE TITLE
Branching taskThree

### ISSUE THREAD

**Issue by Andrei-Luksha2** [YuriZayets/Java_Basic#4]
taskThree(1, 0, 2, 0, 3, 0) возвращает false, хотя точки лежат на оси x

Координаты здесь, наверно, всё же следовало как double делать.
И double сравнивать через строгое равенство в таких задачах не рекомендуют, т.к. из-за разных погрешностей при вычислениях числа могут получаться очень близкими, но не полностью равными. Тогда, обычно на "равенство" проверяют как-то так: `Math.abs(a - b) < 1e-10`

**Comment by YuriZayets** [comment]
Починил, вынес проверку равенства в отдельный метод и переделал принимаемые параметры на double.
